### PR TITLE
Adding endpoint for "set-foreground-overlay" feature

### PR DESCRIPTION
**Pull request by samuelp-mw**
## Description of the PR

This PR provides a way for a user to set an overlay in the foreground of the user.

## Type of change

* [ ] : Technical
* [x] : Feature
* [ ] : Documentation
* [ ] : Bugfix

## Screenshots

https://user-images.githubusercontent.com/79834730/111334197-a440c000-8673-11eb-8292-8d58dc0926bb.mp4

+ Flexible overlay size :

https://user-images.githubusercontent.com/79834730/111494178-8c823e00-873e-11eb-81e0-a9703448dca6.mp4

## Checklist

- [x] : Changes have been tested with Firefox, Chrome and Microsoft Edge
- [x] : PR ready for reviews

## Issues to clarify before merge

- [x] : **Text in the overlay** - The track is directly being overwritten with the overlay before being sent to each participant. This has for disadvantage that any mirroring happening after (like it is systematically done for the local participant track) will make the text appearing in a reversed order. This issue cannot really be solved directly in an easy manner. The only solution would be to let every participants apply the overlay by themselves : However this solution requires a really good synchornization and further implementation effort. Any text on the video track would also appear in a mirrored manner for the local participant. Should this issue be adressed? **The local flip does not look to be applied all the time and this problem is there only in case this is activated. This will need further investigation. The possibility to manually flip the video track offers also manual/temporary solution to this problem.**
- [x] : Should a toggle button be added (with default options)? **A UI PR will be created later to create a version accssible to the community.**

### CODE REVIEW

**Comment by ivicos-friedrich** [comment]
I am unsure if the circle isn't a little bit too small. How do you feel about this? Maybe have two shapes circle and big-circle?

**Comment by samuelp-mw** [comment]
> I am unsure if the circle isn't a little bit too small. How do you feel about this? Maybe have two shapes circle and big-circle?

Thanks for the review Friedrich. For now the diameter of the circle is defined to 70% of the height. I can try multiple ratio and will post some screenshots here. As you said we can also keep multiple sizes for more flexibility. 
Something that could also be done is defining the shape like this circle-ratio where ratio is a percentage of the max size, How do you think? I guess the last option could certainly be nice to have right?

**Comment by ivicos-friedrich** [comment]
> > I am unsure if the circle isn't a little bit too small. How do you feel about this? Maybe have two shapes circle and big-circle?
> 
> Thanks for the review Friedrich. For now the diameter of the circle is defined to 70% of the height. I can try multiple ratio and will post some screenshots here. As you said we can also keep multiple sizes for more flexibility.
> Something that could also be done is defining the shape like this circle-ratio where ratio is a percentage of the max size, How do you think? I guess the last option could certainly be nice to have right?

I like the idea of having circle-ratio as a shape! Its probably the most flexible option

**Comment by samuelp-mw** [comment]
> > > I am unsure if the circle isn't a little bit too small. How do you feel about this? Maybe have two shapes circle and big-circle?
> > 
> > 
> > Thanks for the review Friedrich. For now the diameter of the circle is defined to 70% of the height. I can try multiple ratio and will post some screenshots here. As you said we can also keep multiple sizes for more flexibility.
> > Something that could also be done is defining the shape like this circle-ratio where ratio is a percentage of the max size, How do you think? I guess the last option could certainly be nice to have right?
> 
> I like the idea of having circle-ratio as a shape! Its probably the most flexible option

Ok! I will implement it that way ;)

Small question : The way I chose to implement is to add an effect/overlay to the video track before it being sent to the other participants. Problem : it happens that the track is mirrored for the local participant, meaning that if I put a ivicos logo on the overlay for example, there is a risk that this one will be reversed (only) for the local participant (when he looks at his own video track). I don t see really a lot of way to avoid that. It happened to me multiple times but I could not reproduce it the last times. Any idea to solve that if this case comes again?

The other totally different solution could have been to apply the overlay in each participant FE but the complexity is really higher in that case.

**Comment by ivicos-friedrich** [comment]
> Problem : it happens that the track is mirrored for the local participant, meaning that if I put a ivicos logo on the overlay for example, there is a risk that this one will be reversed (only) for the local participant (when he looks at his own video track). I don t see really a lot of way to avoid that. It happened to me multiple times but I could not reproduce it the last times. Any idea to solve that if this case comes again?

If you right click on your track you can invert it by pressing "flip" or at least in the version of jitsi we have currently deployed. So maybe that fixes the issue? Not sure.

**Comment by samuelp-mw** [comment]
> > Problem : it happens that the track is mirrored for the local participant, meaning that if I put a ivicos logo on the overlay for example, there is a risk that this one will be reversed (only) for the local participant (when he looks at his own video track). I don t see really a lot of way to avoid that. It happened to me multiple times but I could not reproduce it the last times. Any idea to solve that if this case comes again?
> 
> If you right click on your track you can invert it by pressing "flip" or at least in the version of jitsi we have currently deployed. So maybe that fixes the issue? Not sure.

Yes you are right. The user will unfortunately be able only to do it manually as I don t think we should deactivate the automatic mirroring : it s always better for the local user to have like a mirror in front of him, right?

Another question : Do we implement a toggle button or not?

**Review by samuelp-mw — COMMENTED** [review]
Flexible size for the overlay shape has been implemented. A demo is visible on the PR overview.

**Comment by ivicos-friedrich** [comment]
We probably should at some point think about what to add to the native jitsi UI to make this feature available for the community. At this point I would feel comfortable with it just being available via the api for now. And after we have made it work in campus we can maybe use our learnings from that to add a UI for the community version :)

**Comment by samuelp-mw** [comment]
> We probably should at some point think about what to add to the native jitsi UI to make this feature available for the community. At this point I would feel comfortable with it just being available via the api for now. And after we have made it work in campus we can maybe use our learnings from that to add a UI for the community version :)

Yes. I agree, It turns out that there is currently a lot going on on the community version : I saw many commits in the last days replacing the background blurring with virtual backgrounds (like for Teams) and apparently creating a UI for that (choosing background). That could be a nice starting point for us. I have not tested it yet though.

**Pull request merged**
